# Generated by Django 3.2 on 2022-02-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrival',
        ),
    ]
