# Generated by Django 3.2 on 2022-02-13 19:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2147483647', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
