# Generated by Django 3.2 on 2022-02-14 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
