# Generated by Django 3.2 on 2022-01-16 17:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20220116_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['email', 'date', 'time'], unique=True),
        ),
    ]
