# Generated by Django 3.2 on 2022-01-16 17:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='email'),
        ),
    ]
