# Generated by Django 3.2 on 2022-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(max_length=200),
        ),
    ]
