# Generated by Django 3.2 on 2022-02-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
