# Generated by Django 3.2 on 2022-02-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_rename_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
