# Generated by Django 3.2 on 2022-02-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='url',
        ),
    ]
