# Generated by Django 3.2 on 2022-02-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
    ]
