# Generated by Django 3.2 on 2022-02-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_booking_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrival',
        ),
    ]
