# Generated by Django 3.2 on 2022-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menustarter',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='menustarter',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
