# Generated by Django 3.2 on 2022-02-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220223_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuStarter',
            new_name='Starter',
        ),
    ]
