# Generated by Django 3.2 on 2022-02-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
