# Generated by Django 3.2 on 2022-02-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_drinks_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='starter',
            name='display',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=1),
            preserve_default=False,
        ),
    ]
