# Generated by Django 3.2 on 2022-02-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20220223_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.IntegerField(choices=[(0, 'Softdrink'), (1, 'Hotdrink'), (2, 'Alcohol'), (3, 'Wine'), (4, 'Spirit')], default=0),
            preserve_default=False,
        ),
    ]
