# Generated by Django 3.2 on 2022-02-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_drink_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
